name: Distribution

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout LinkedIn Cruise Control for Apache Kafka
        uses: actions/checkout@v2
        with:
           repository: linkedin/cruise-control
           ref: ${{ github.ref }}
           path: cruise-control-${{ github.ref }}
      
      - name: Build main distribution
        run: ./gradlew --console=plain jar
        working-directory: cruise-control-${{ github.ref }}

      - name: Build metrics distribution
        run: ./gradlew --console=plain jar copyDependantLibs
        working-directory: cruise-control-${{ github.ref }}
      
      - name: Remove source and compiled files
        run: rm -fr .circleci/ .git/ .gradle/ build.gradle buildSrc/ checkstyle/ cruise-control/src/ cruise-control/build/classes/ cruise-control/build/resources/ cruise-control/build/tmp/ cruise-control-core/src/ cruise-control-core/build/classes/ cruise-control-core/build/resources/ cruise-control-core/build/tmp/ cruise-control-metrics-reporter/src/ cruise-control-metrics-reporter/build/classes/ cruise-control-metrics-reporter/build/resources/ cruise-control-metrics-reporter/build/tmp/ docs/ gradle/ gradle.properties gradlew gradlew.bat semantic-build-versioning.gradle settings.gradle
        working-directory: cruise-control-${{ github.ref }}
      
      - name: Archive distribution
        run: tar cfz linkedin-cruise-control-${{ github.ref }}.tgz cruise-control-${{ github.ref }}
      
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linkedin-cruise-control-${{ github.ref }}.tgz
          asset_name: linkedin-cruise-control-${{ github.ref }}.tgz
          asset_content_type: application/x-gzip
